### ISSUE TITLE
Bug in testTrans function

### ISSUE THREAD

**Issue by quantitative-technologies** [mtkurbucz/LLT#1]
When I prepared my own data as described in the paper, and then run your code I am getting an error:

```r
> result <- testTrans(llt_data_dir, train_test, train_law, select = select, lag = lag)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 2950, 5730
```

The error occurs at the line:

```r
 out <- cbind(id, out)
```
where `id` and `out` do not match. 

I can see in the code that the variable `id` is being "stepped on" at each step of the outer loop, which did not seem correct. But I haven't had a chance to inspect further.

**Comment by mtkurbucz** [comment]
Thanks. I fixed an indexing error in the `testTrain` function. I believe it caused the problem, and it should work now.

**Comment by mtkurbucz** [comment]
Thanks. I fixed an indexing error in the `testTrain` function. I believe it caused the problem, and it should work now.

**Comment by quantitative-technologies** [comment]
Thanks, there is no error now on my dataset.
